### ISSUE TITLE
Install error on clean, up to date system

### ISSUE THREAD

**Issue by alexshires** [rootpy/root_numpy#164]
Hi,

I'm trying to install root-numpy on a clean, up-to-date system (Ubuntu 14.10) and get the following error, which is something to do with the gcc (11 or not) compiler flags.

https://gist.github.com/alexshires/2481d1368ffb90c2b105

I'm using ROOT6 (trunk) and the following versions:

uname -a
Linux greyarea 3.16.7-x86_64-linode49 #3 SMP Fri Nov 14 16:55:37 EST 2014 x86_64 x86_64 x86_64 GNU/Linux
:~$ g++ --version
g++ (Ubuntu 4.9.1-16ubuntu6) 4.9.1
:~$ gcc --version
gcc (Ubuntu 4.9.1-16ubuntu6) 4.9.1
:~$ python --version
Python 2.7.8

Any thoughts on how to resolve this?

Regards,

Alex

**Comment by kratsg** [comment]
Hi @alexshires, I already know ROOT6 still has problems when I've done some dev work using AthenaBase. Can you try with ROOT5 instead and see if it works?

Otherwise, if there's a reason for ROOT6, you might need to add some compiler flags to explicitly provide C++11 support:

```-std=c++11```

because that's the errors you're getting.

**Comment by ndawe** [comment]
I'm setting up ROOT6 + gcc 4.9 on my Ubuntu system and will run some tests. I think I just need to add some logic in the `setup.py` to add the flag `'-std=c++11'` to `extra_compile_args` if the version of gcc is at least 4.9.

**Comment by alexshires** [comment]
Hi,

@kratsg: Yes, LHCb is gradually moving to ROOT6 for Run II so it's time to embrace it for me...!

I've added 

```
diff --git a/setup.py b/setup.py
index 39577bc..94743a9 100755
--- a/setup.py
+++ b/setup.py
@@ -37,6 +37,7 @@ os.chdir(local_path)
 sys.path.insert(0, local_path)
 
 
+
 def root_flags(root_config='root-config'):
     root_inc = subprocess.Popen([root_config, '--incdir'],
         stdout=subprocess.PIPE).communicate()[0].strip()
@@ -60,6 +61,18 @@ except OSError:
             "ROOTSYS is {0} but running {1} failed".format(
                 rootsys, root_config))
 
+
+# this assumes a consistent API for the (--version) call??
+def gcc_version( ) :
+    gccout = subprocess.Popen(['g++','--version'],
+        stdout=subprocess.PIPE).communicate()[0].strip()
+    #print gccout.split()[3].replace('.','')
+    return gccout.split()[3].replace('.','')
+cpp_flags = []
+if gcc_version() > 480 :
+    cpp_flags += [ '--std=c++11']
+#print cpp_flags
+
 librootnumpy = Extension('root_numpy._librootnumpy',
     sources=[
         'root_numpy/src/_librootnumpy.cpp',
@@ -70,9 +83,11 @@ librootnumpy = Extension('root_numpy._librootnumpy',
         np.get_include(),
         root_inc,
         'root_numpy/src'],
-    extra_compile_args=['-Wno-unused-function'],
+    extra_compile_args=['-Wno-unused-function'] + cpp_flags,
     extra_link_args=root_ldflags + ['-lTreePlayer'])
 
+
+
 # check for custom args
 filtered_args = []
 release = False
```

and it installs nicely. It assumes gcc --version returns a consistent format but other than that, it's ok.

Would you like me to commit?

**Comment by alexshires** [comment]
or better - reply on the ROOT version?

```
diff --git a/setup.py b/setup.py
index 39577bc..cae3f54 100755
--- a/setup.py
+++ b/setup.py
@@ -37,15 +37,18 @@ os.chdir(local_path)
 sys.path.insert(0, local_path)
 
 
+
 def root_flags(root_config='root-config'):
     root_inc = subprocess.Popen([root_config, '--incdir'],
         stdout=subprocess.PIPE).communicate()[0].strip()
     root_ldflags = subprocess.Popen([root_config, '--libs'],
         stdout=subprocess.PIPE).communicate()[0].strip().split(' ')
-    return root_inc, root_ldflags
+    root_version = subprocess.Popen([root_config, '--version']
+            , stdout=subprocess.PIPE).communicate()[0].strip()
+    return root_inc, root_ldflags, root_version
 
 try:
-    root_inc, root_ldflags = root_flags()
+    root_inc, root_ldflags, root_version = root_flags()
 except OSError:
     rootsys = os.getenv('ROOTSYS', None)
     if rootsys is None:
@@ -60,6 +63,10 @@ except OSError:
             "ROOTSYS is {0} but running {1} failed".format(
                 rootsys, root_config))
 
+more_compile_args = ['-Wno-unused-function']
+if root_version.startswith('5') or root_version.startswith('6'):
+        more_compile_args.append('-std=c++11')
+
 librootnumpy = Extension('root_numpy._librootnumpy',
     sources=[
         'root_numpy/src/_librootnumpy.cpp',
@@ -70,8 +77,10 @@ librootnumpy = Extension('root_numpy._librootnumpy',
         np.get_include(),
         root_inc,
         'root_numpy/src'],
-    extra_compile_args=['-Wno-unused-function'],
-    extra_link_args=root_ldflags + ['-lTreePlayer'])
+    extra_compile_args = more_compile_args,
+    extra_link_args = root_ldflags + ['-lTreePlayer'])
+
+
 
 # check for custom args
 filtered_args = []
```

**Comment by kratsg** [comment]
@alexshires -- @ndawe will add the testing himself (he's got a procedure for it) and set up jenkins [most likely] to add this. I believe it won't be a new `root_numpy` version until the first stable release of ROOT6 comes out.

Do you know when you're expected to fully use ROOT6 for LHCb? I ask because it won't come out of beta until the end of the month, with ROOT6.2(ish) coming out at the end of February. ROOT6.2 will be most likely the one I suggest people to use.

ATLAS won't be switching to ROOT6 soon as we're gearing up on using our new dataset formats ;)

**Comment by alexshires** [comment]
AFAIK, the legacy software stack is all ROOT5, but the hope is that all Run II software will be ROOT 6 / C++11 compatible. Our current stack is built against it at the moment and we're dropping the ROOT5 builds when we can. I agree, ROOT6.2 will be a good point to convert and sort out any compatibility issues

**Comment by piti118** [comment]
Thanks for tracking down the problem.

However, this is a compiler issue. So, it has to be fixed using compiler version condition not ROOT version condition if you look at the error message it is clearly the header /usr/include/c++/4.9/bits/atomic_base.h that complains.

Yet, the way you proposed to detect gcc version will fail if ppl use other compiler and parsing the output is unreliable for example gcc on mac is really clang and will print something like this. Not to mention Windows ppl probably doesn't even have gcc.

```
piti@MBPKun:Lecture$gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.56) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin14.0.0
Thread model: posix
```

I believe there is a proper way to do this doing something along this line
http://stackoverflow.com/questions/724664/python-distutils-how-to-get-a-compiler-that-is-going-to-be-used
We will need to figure out how to get the version though (I believe there `should` be something like self.compiler.version or something along that line).

**Comment by piti118** [comment]
Wait.. actully i'm wrong from ROOT6 requirement.
```
g++
(ROOT 6 requires g++ 4.8 or clang 3.4; for SLC5/SLC6, gcc 4.8 is available in the developer toolset)
for /usr/bin/g++
```

So really every program that links with root will need that flag and I believe someone should have already put something in root-config script to give out this flag if necessary.

**Comment by kratsg** [comment]
@piti118 I think we'll need to assume that if someone is using ROOT6, they have the appropriate compilers in place for it. So something like

```
if root_version.startswith('6'):
    more_compile_args.append('-std=c++11')
```

should be satisfactory. I don't quite see a way around it and I don't think we have anything that specifically requires c++11 anyway (unless we use `auto` variables and the like).

**Comment by piti118** [comment]
I'm worried about clang people (aka almost all mac users) with appropriate clang version whether it has std=c++11.

**Comment by kratsg** [comment]
Quickly googled: http://stackoverflow.com/a/10602859 -- it seems like we should be ok presuming appropriate clang versions. I believe ROOT6 requires a recent version of clang for the Mac users -- but I should check this on one of my Macs later this week.

**Comment by ndawe** [comment]
Bah, problems with ROOT 6.02 when building a prefix installation (missing header and now segmentation violation). Trying the master branch now. @alexshires did you have similar issues? Gone are the days of a quick ROOT compilation....

**Comment by ndawe** [comment]
I am able to get root_numpy to build against ROOT6 with the changes I have made in #165, but I'm running up against some other problem now.

**Comment by alexshires** [comment]
Hey, the head of ROOT6 build fine for me! What's your current error?

**Comment by ndawe** [comment]
The head builds now for me too. Are you seeing similar problems with PyROOT and ROOT6 as I am in #165?

**Comment by ndawe** [comment]
It would be great if you could try running the unit tests on your setup. Just run ``make``.

**Comment by kratsg** [comment]
Since #165 is closed. I am going to close this issue. @alexshires -- file a new issue if there are still problems and tag #164 in it.

**Comment by alexshires** [comment]
Thanks! I can confirm it works fine for me now. I looked at #165 -- ouch!

**Comment by kratsg** [comment]
@alexshires Tell me about it. I've spent the past 6 months slaving through experimental features all over the place with the new changes moving towards ROOT6. This is the least of our problems these days.
