### ISSUE TITLE
Variable-length arrays of type `unsigned short` causing crash

### ISSUE THREAD

**Issue by quantumfieldtrip** [rootpy/root_numpy#171]
Hi everyone,

Whenever I try loading a ROOT file with a variable-length 1D array of type `unsigned short`, root_numpy will cause Python to crash with this error message

    Python(74303,0x7fff7d3c3310) malloc: *** error for object 0x7f8abe3bd9c8: incorrect checksum for freed object - object was probably modified after being freed.
    *** set a breakpoint in malloc_error_break to debug

This doesn't happen with variable-length 1D arrays of any other types (as far as I know). Here is an example script that generates a ROOT file with variable-length 1D arrays of different types (run with `root -l var_array.c`).

`var_array.c`:

    #include "TFile.h"
    #include "TTree.h"

    void write() {

      const unsigned int max_capacity = 500;
      int elements;
      short short_[max_capacity];
      unsigned short ushort_[max_capacity];
      int int_[max_capacity];
      unsigned int uint_[max_capacity];
      long long_[max_capacity];
      unsigned long ulong_[max_capacity];
      float float_[max_capacity];
      double double_[max_capacity];
      bool bool_[max_capacity];

      TFile f("var_array.root", "recreate");
      TTree * t = new TTree("t", "");
      // http://root.cern.ch/root/html/TBranch.html#TBranch:TBranch@2
      t->Branch("elements", &elements, "elements/I");
      t->Branch("short_", short_, "short_[elements]/S");
      t->Branch("ushort_", ushort_, "ushort_[elements]/s");  // removing this line will make root_numpy run smoothly
      t->Branch("int_", int_, "int_[elements]/I");
      t->Branch("uint_", uint_, "uint_[elements]/i");
      t->Branch("long_", long_, "long_[elements]/L");
      t->Branch("ulong_", ulong_, "ulong_[elements]/l");
      t->Branch("float_", float_, "float_[elements]/F");
      t->Branch("double_", double_, "double_[elements]/D");
      t->Branch("bool_", bool_, "bool_[elements]/O");

      for (int i = 0; i < 1000; i++) {
        int rand = gRandom->Rndm() * (max_capacity-1);
        elements = rand;
        for (int j = 0; j < elements; j++) {
          short_[j] = 1;
          ushort_[j] = 1;
          int_[j] = 1;
          uint_[j] = 1;
          long_[j] = 1;
          ulong_[j] = 1;
          float_[j] = 1.0;
          double_[j] = 1.0;
          bool_[j] = true;
        }
        t->Fill();
      }
      t->Print();
      f.cd();
      t->Write();
    }

    void var_array()
    {
      write();
    }

If I try loading the generated ROOT file with root_numpy

    from root_numpy import root2array
    root2array("var_array.root")

I'll get the error shown at the top of this post. However, if I remove the line

          t->Branch("ushort_", ushort_, "ushort_[elements]/s");  // removing this line will make root_numpy run smoothly

from `var_array.c`, everything will work just fine.

**Comment by ndawe** [comment]
Thanks for reporting! I will try to reproduce this on my end.

**Comment by kratsg** [comment]
This ROOT file doesn't quite have the standard structure I expect (it's actually pretty hard for me to jump around in it on my end). Is there a reason you're using root2array instead of tree2array?

I can at least confirm it breaks though:

```
python
Python 2.7.8 (default, Oct 19 2014, 16:03:53) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.51)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import root_numpy as rnp
>>> from ROOT import TFile
>>> f = TFile("var_array.root")
>>> t = f.Get("t")
>>> f
<ROOT.TFile object ("var_array.root") at 0x7fe86ab21170>
>>> t
<ROOT.TTree object ("t") at 0x7fe86ac6f860>
>>> rnp.tree2array(t)
python(35149,0x7fff7704f310) malloc: *** error for object 0x7fe86cf54408: incorrect checksum for freed object - object was probably modified after being freed.
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6
```

**Comment by ndawe** [comment]
Yup:

```
>>> from root_numpy import root2array
>>> root2array('var_array.root')
*** Error in `python': malloc(): memory corruption: 0x0000000001dfe4d0 ***
Aborted
```

**Comment by ndawe** [comment]
I think I found the cause of this bug. One sec...

**Comment by ndawe** [comment]
Fixed. Typo here in root_numpy/src/tree.pyx:

```
--- a/root_numpy/src/tree.pyx
+++ b/root_numpy/src/tree.pyx
@@ -5,7 +5,7 @@ TYPES = {
     TypeName[char]().name:               ('char',               np.dtype(np.int8),      np.NPY_INT8),
     TypeName[unsigned_char]().name:      ('unsigned char',      np.dtype(np.uint8),     np.NPY_UINT8),
     TypeName[short]().name:              ('short',              np.dtype(np.int16),     np.NPY_INT16),
-    TypeName[unsigned_short]().name:     ('unsigned short',     np.dtype(np.uint16),    np.NPY_UINT8),
+    TypeName[unsigned_short]().name:     ('unsigned short',     np.dtype(np.uint16),    np.NPY_UINT16),
     TypeName[int]().name:                ('int',                np.dtype(np.int32),     np.NPY_INT32),
     TypeName[unsigned_int]().name:       ('unsigned int',       np.dtype(np.uint32),    np.NPY_UINT32),
     TypeName[long]().name:               ('long',               np.dtype(np.int64),     np.NPY_INT64),
```

**Comment by ndawe** [comment]
I'm adding this to the test coverage and will tag and release.

**Comment by kratsg** [comment]
Hilarious typo. Here's a stack trace to confirm (with pdb)

https://gist.github.com/kratsg/11be7d90b7f1ddb6ff20

**Comment by ndawe** [comment]
Yeah, not all types are tested with the test files created by generate.cxx.

**Comment by kratsg** [comment]
How did you figure out it might have been that? It didn't seem totally obvious in hindsight. I could've thought it might potentially be due to the variable length arrays since NumPy is very finicky about that.

**Comment by ndawe** [comment]
That dict mapping C and numpy types came to mind. That really is the only place that should differentiate between basic types (except for the special case of the Boolean).

**Comment by ndawe** [comment]
@quantumfieldtrip this is now fixed on the master branch. I'll tag and release. Congratulations on being the first to use root_numpy on arrays of unsigned shorts :smile:.

**Comment by ndawe** [comment]
3.4.1 is released with this fixed.
