### ISSUE TITLE
Is there python 3 support?

### ISSUE THREAD

**Issue by vsilv** [rootpy/root_numpy#176]
I am just wondering, maybe this was answered somewhere else. Thank you in advance

**Comment by ndawe** [comment]
Not yet. This will take some PyCObject -> PyCapsule conversion in the various .pyx. I'm taking a look at this over the coming days... I also want to make the switch to py3 sooner rather than later, but the majority of users are still in py2 land.

**Comment by ndawe** [comment]
Working on this in #177

**Comment by kratsg** [comment]
Whoops, my bad - I misclicked!

**Comment by ndawe** [comment]
No problem! Getting close.. working on what I see as the last problem to overcome...

**Comment by ndawe** [comment]
@vsilv this is now done in #177. Feel free to test from my py3 branch before we merge into master.

**Comment by kratsg** [comment]
@ndawe -- Few comments:

- `six.py` is what you use to have the cython working in python 2 and python 3? I thought it was for python projects.. not cython projects.
- We need to support ROOT=5-34-25 ; this is the final root version being used before Run 2 commences. I believe Root5 is now closed for support and bugs there will not be fixed anymore. Root6 is being fully developed.
- explain the switch between `basestring` and `string_types` ? In particular, what's going on here that you changed the type outright: https://github.com/rootpy/root_numpy/pull/177/files#diff-06942ee9ba64664fb84fa1b8cd8ce667L87 [looking at PY2 versus PY3, those are major differences that it seems confusing]

I'm mostly more worried about the ROOT versions. There have been a lot of huge bug fixes related to PyROOT in ROOT 5.34/25 that help with the newer AOD files that people will eventually be using (if they're not using ROOT6).

**Comment by ndawe** [comment]
#177 is merged. Python 3 support is in.
