### ISSUE TITLE
Read from remote root file

### ISSUE THREAD

**Issue by tata-antares** [rootpy/root_numpy#191]
I try to use root_numpy for reading remote root file

filename = 'root://eospublic.cern.ch//eos/opendata/cms/Run2010B/Mu/AOD/Apr21ReReco-v1/0000/00459D48-EB70-E011-AF09-90E6BA19A252.root'
root_numpy.list_trees(filename)

And I got the error:
ERROR:ROOT.TUnixSystem.DynamicPathName:Netx[.so | .dll | .dylib | .sl | .dl | .a] does not exist in /usr/local/lib/root:.:/usr/local/lib/root::/usr/local/lib/root/cint/cint/stl

Is it possible read it? TChain correctly read the root file.

**Comment by ndawe** [comment]
Thanks for reporting. I get the same error, and this also fails:

```python
>>> from ROOT import TFile
>>> f = TFile.Open(filename)
Error in <TUnixSystem::FindDynamicLibrary>: NetxNG[.so | .dll | .dylib | .sl | .dl | .a] does not exist in ...
```

Are you sure that TChain is reading your file? I still get this:

```python
>>> c = TChain()
>>> c.Add(filename)
1
>>> c.GetEntries()
Error in <TUnixSystem::FindDynamicLibrary>: NetxNG[.so | .dll | .dylib | .sl | .dl | .a] does not exist ...
```

For some reason, libNetxNG.so is not being built when compiling ROOT. This looks to be the same issue: https://github.com/Homebrew/homebrew-science/issues/1130

I'd expect this to work fine in root_numpy as long as ROOT has the appropriate libraries available.

**Comment by tata-antares** [comment]
Thank you for answer!

Indeed the problem was in libNetxNG.so. I followed your link and now it is ok. 

By the way, root_numpy can read, for example, EventAuxiliary.id_.luminosityBlock_ (similar to https://root.cern.ch/phpBB3/viewtopic.php?f=3&t=15868) without any edm::EventAuxiliary class and without CMS virtual machine (http://opendata.cern.ch/VM/CMS, http://opendata.cern.ch/getting-started/CMS). Keep it up!

**Comment by kratsg** [comment]
@tata-antares - as far as reading that, it's just more or less a branch. As long as PyROOT, in general, can read and access the branches -- so can `root_numpy`. The only problems I've seen are when you have branches of pointers instead which is happening with a lot of the new EDM changes, and that makes things a little more difficult.

**Comment by tata-antares** [comment]
The initial problem was to read this branch direct `EventAuxiliary.id_.luminosityBlock_`. 

For example, reading `recoCaloJets_ak5CaloJets__RECO.obj.pt_` is simple. TTree contains branch `recoCaloJets_ak5CaloJets__RECO.`, so it is possible:

    tree.GetEntry(n)
    tree.GetBranch('recoCaloJets_ak5CaloJets__RECO.obj.pt_').GetLeaf(
                   'recoCaloJets_ak5CaloJets__RECO.obj.pt_').GetValue()

But for EventAuxiliary it doesn't work. TTree contains `EventAuxiliary`.

    tree.GetBranch('EventAuxiliary').GetLeaf('EventAuxiliary').GetValue()

which return `edm::EventAuxiliary` structure.

Do you know, how to read `EventAuxiliary.id_.luminosityBlock_` using PyROOT?

**Comment by kratsg** [comment]
Well, I'm ATLAS-side. I don't know if I can get access to your file, but it honestly sounds like CMS isn't providing backwards-compatibility when they store these kinds of custom objects in the file (at least not as much as how ATLAS is doing it, which is expected). If you're able to retrieve an `edm::EventAuxiliary` structure using PyROOT, that implies PyROOT knows the type, otherwise it would've have thrown an error (I think).

**Comment by ndawe** [comment]
@tata-antares great to hear it works now! I'll make this issue as a ROOT issue and will close this.

I'll have a look at that opendata CMS file and will try to read ``EventAuxiliary.id_.luminosityBlock_``

**Comment by tata-antares** [comment]
Thanks! 

I tried to read root by PyROOT in the same way as you are doing in root_numpy, but can't reproduce it. That is why for me very interesting how to read without root_numpy using standard ROOT (without CMS virtual machine, in which necessary classes exist)

**Comment by ndawe** [comment]
Nice:
```python
>>> arr = root2array("root://eospublic.cern.ch//eos/opendata/cms/Run2010B/MuOnia/AOD/Apr21ReReco-v1/0001/002041B8-FF77-E011-8A94-00215E21EC4A.root", "Events", branches="EventAuxiliary.id_.luminosityBlock_")
>>> arr
array([ 425.,  425.,  425., ...,  434.,  434.,  434.])
>>> len(arr)
12453
```

root_numpy is able to do this because any branch names that don't match up with actual names of branches in the tree are automatically considered as TTreeFormula expressions. So anything that TTreeFormula understands, root_numpy will convert to a column of doubles.
