### ISSUE TITLE
root_numpy.tmva doesn't work without factory.PrepareTrainingAndTestTree

### ISSUE THREAD

**Issue by tata-antares** [rootpy/root_numpy#198]
Hello!

I'm experimenting with tmva-related functions, try to run this example https://github.com/rootpy/root_numpy/blob/master/examples/tmva/plot_twoclass.py. It works. But I don't want to use `factory.PrepareTrainingAndTestTree` (as you can see I don't use it here https://github.com/yandex/rep/blob/master/rep/estimators/_tmvaFactory.py). To clarify, if I don't use it:
```python
add_classification_events(factory, X_train, y_train, weights=w_train) # add all data for training
add_classification_events(factory, X_test, y_test, weights=w_test, test=True) #add all data for testing
```
In this case I get an error during training: `' <FATAL> Factory: No input data for the training provided!'
***> abort program execution`

Maybe I can just add training data by 
```python
add_classification_events(factory, X_train, y_train, weights=w_train) # add all data for training
```
without adding test and without using factory.PrepareTrainingAndTestTree? (in the latter case the same fatal error arises)

I don't know much details about TMVA implementations, so probably there exist some simple solution.

**Comment by ndawe** [comment]
Yes, TMVA requires some internal setup if the trees were assigned on an event-by-event basis

In Factory.cxx:

```C++
 630 void TMVA::Factory::PrepareTrainingAndTestTree( const TCut& cut, const TString& opt )
 631 {                                                                               
 632    // prepare the training and test trees                                       
 633    // -> same cuts for signal and background                                    
 634    SetInputTreesFromEventAssignTrees();                                         
 635                                                                                 
 636    DefaultDataSetInfo().PrintClasses();                                         
 637    AddCut( cut );                                                               
 638    DefaultDataSetInfo().SetSplitOptions( opt );                                 
 639 }
```

The important function all in there is ``SetInputTreesFromEventAssignTrees();``, but that method is private, so we can't call it directly.

If you set the trees in the first place, then calling this is unnecessary. But SetInputTreesFromEventAssignTrees isn't expensive:

```C++
 354 void TMVA::Factory::SetInputTreesFromEventAssignTrees()                         
 355 {                                                                               
 356    // assign event-wise local trees to data set                                 
 357    UInt_t size = fTrainAssignTree.size();                                       
 358    for(UInt_t i=0; i<size; i++) {                                               
 359       if(!UserAssignEvents(i)) continue;                                        
 360       const TString& className = DefaultDataSetInfo().GetClassInfo(i)->GetName();
 361       SetWeightExpression( "weight", className );                               
 362       AddTree(fTrainAssignTree[i], className, 1.0, TCut(""), Types::kTraining );
 363       AddTree(fTestAssignTree[i], className, 1.0, TCut(""), Types::kTesting );  
 364    }                                                                            
 365 }
```

**Comment by ndawe** [comment]
I'm wondering if it's possible to avoid creating a Factory altogether and instead construct and train a Method directly.

**Comment by tata-antares** [comment]
Thanks! 

I added factory.PrepareTrainingAndTestTree(TCut("1"), ""). It works. 

And another thing: why do you not add factory.AddTarget('y', 'F') directly into add_regression_events? I think, you reserve 'y' label for target column, so it will be logical to set a target label by yourself.

**Comment by tata-antares** [comment]
And for `kCuts` method it is necessary to use `reader.EvaluateMVA(method_name, signal_efficiency)` - we must put `signal_efficiency` parameter, float number ranges [0, 1]. How this is done in `evaluate_reader`?

**Comment by ndawe** [comment]
> And another thing: why do you not add factory.AddTarget('y', 'F') directly into add_regression_events? I think, you reserve 'y' label for target column, so it will be logical to set a target label by yourself.

I think it's best to leave this up to the user. The function assumes that the user has already called AddTarget for each target in the dataset (TMVA can handle multiple targets). This could all be hidden away in your wrapper class in REP.

> we must put signal_efficiency parameter, float number ranges [0, 1]. How this is done in evaluate_reader?

Ah, good point. I missed this. I'm adding this now and will make a new tag.

**Comment by tata-antares** [comment]
> I think it's best to leave this up to the user. The function assumes that the user has already called AddTarget for each target in the dataset (TMVA can handle multiple targets). This could all be hidden away in your wrapper class in REP.

Yep, I will hide it in REP. 

Another question:
For example, I have multiple targets and do 
```python
factory.AddTarget('y', 'F')`
factory.AddTarget('target2', 'F')
add_regression_events(data, y_labels)
```
How can I add `target2` to factory in this case? And do you guarantee that TMVA target will have name `'y'` in case of `add_regression_events(data, y_labels)`? 

By the way, why do you not do the possibility `add_regression_events(data, target)`, where target can be `ndarray`? This seems a comfortable way to add data with targets or multiple targets.

**Comment by tata-antares** [comment]
By the way,

```python
add_classification_events(factory, X_train, y_train, weights=w_train)
factory.PrepareTrainingAndTestTree(TCut("1"), "")
```
doesn't work:
```python
--- Factory                  : 
--- DataSetInfo              : Added class "Signal"      with internal class number 0
--- DataSetInfo              : Added class "Background"  with internal class number 1
--- Factory                  : Add Tree TrainAssignTree_Signal of type Signal with 999 events
--- Factory                  : Add Tree TestAssignTree_Signal of type Signal with 0 events
--- <FATAL> DataInputHandler         : Encountered empty TTree or TChain of class Signal
***> abort program execution
```

The same was when I add TTree by hand to factory: I needed to add Train and Test trees.

For me it is strange that factory must have test samples to train estimators. Maybe it is needed to add some comments about this to your examples to avoid some confusion.

**Comment by ndawe** [comment]
For regression with multiple targets, just use ``add_regression_events(data, targets)`` where targets is a 2-dimensional array of shape (n_events, n_targets). So something like ``numpy.c_[target1, target2]``. The columns must be in the same order as you called AddTarget for each target.

Yes, I agree that it's strange that test samples are required, even if you don't want to use TMVA's TestAllMethods(). I can comment on this in the docs. There might also be some way to train methods without using a Factory, or a way to set the dataset without dealing with AddTree and to avoid the check for the test trees.

**Comment by ndawe** [comment]
4.1.2 is released with the aux MethodCuts parameter included in evaluate_reader and evaluate_method.

**Comment by tata-antares** [comment]
Good! It works. 

I still don't understand why you don't hide `factory.AddTarget('y', 'F')` in the `add_regression_events`. What is advantage I have calling `AddTarget`?

Thanks.

**Comment by ndawe** [comment]
The function adds the regression events to the factory. That's it. Doing any more than that inside the function would be too much. What if the user doesn't want to call the target "y"? What if they have already called AddTarget()? What naming scheme do you impose for multiple targets? This function is supposed to be a drop-in replacement for looping on a numpy array and adding events on the Python side, and nothing more. It should be easy to integrate into existing code without conflicting with other things. That's why calling this function doesn't have any other effect on a Factory.
