### ISSUE TITLE
fill_hist error

### ISSUE THREAD

**Issue by tibristo** [rootpy/root_numpy#208]
Hi guys,

I get the error
" Error in <TH2D::Fill>: Invalid signature - do nothing"

whenever I use fill_hist with a TH2D histogram.  I thought it was an issue with my code, but I tried running the example on the root_numpy examples webpage:
from ROOT import TH2D, TCanvas
from root_numpy import fill_hist
import numpy as np

# Fill a ROOT histogram from a NumPy array
hist = TH2D('name', 'title', 20, -3, 3, 20, -3, 3)
fill_hist(hist, np.random.randn(1E6, 2))

and I get exactly the same errors.

I'm using Python 2.7.4, gcc 4.8.0, root_numpy 4.2.1 and root 5.34.25.

Any ideas?

EDIT: I upgraded to root_numpy 4.3.0 with pip and it's working now. Sorry for the noise.

Thanks
Tim

**Comment by ndawe** [comment]
Glad that installing 4.3.0 fixed this. Did you upgrade ROOT at any point after previously installing root_numpy? This reminds me of #136.

**Comment by kratsg** [comment]
@ndawe -- one could have actually just upgraded the ROOT version from 5.34.16 up to 5.34.25 (I got an error like this) without reupdating root_numpy.
