### ISSUE TITLE
compile complaining about "thread-local storage"

### ISSUE THREAD

**Issue by jhetherly** [rootpy/root_numpy#209]
Hello,

I'm trying to setup root_numpy with the command:
env CC=clang pip install root_numpy

but, this fails at compilation with:
In file included from root_numpy/src/_librootnumpy.cpp:257:
    In file included from /Users/jhetherly/src/root/build/6_04_02/release/include/TTree.h:62:
    In file included from /Users/jhetherly/src/root/build/6_04_02/release/include/TClass.h:45:
    /Users/jhetherly/src/root/build/6_04_02/release/include/ThreadLocalStorage.h:280:4: error: thread-local storage is not supported for the current target
       TTHREAD_TLS(T*) ptr = NULL;

My specifications are:
computer: MacBook Pro - OSX 10.9.5
ROOT 6.04/02
Python 2.7.10 :: Anaconda 2.3.0 (x86_64)

I have rootpy working perfectly, however this doesn't require a compilation step.

**Comment by ndawe** [comment]
This looks related:

http://stackoverflow.com/a/23850891
https://root.cern.ch/phpBB3/viewtopic.php?t=19538

Be sure to use the same compiler and stdlib as was used to compile your ROOT, python, etc. and one that supports thread-local storage.

**Comment by ndawe** [comment]
Do either of these work? Sorry, I don't have a mac with me.

```
pip install root_numpy
```
or
```
env CC=clang++ pip install root_numpy
```

**Comment by jhetherly** [comment]
Ah, yes. I've seen this post in the ROOT forums as well. I thought moving to 6.04 would bypass that thread altogether. Maybe not. I'll build a "patches" build of ROOT 6.02 to ensure this isn't the case. The two commands give different errors:
pip install root_numpy - 
gcc: error: unrecognized command line option '-stdlib=libc++'
error: command 'gcc' failed with exit status 1

env CC=clang++ pip install root_numpy - 
In file included from root_numpy/src/_librootnumpy.cpp:257:
    In file included from /Users/jhetherly/src/root/build/6_04_02/release/include/TTree.h:62:
    In file included from /Users/jhetherly/src/root/build/6_04_02/release/include/TClass.h:45:
    /Users/jhetherly/src/root/build/6_04_02/release/include/ThreadLocalStorage.h:280:4: error: thread-local storage is not supported for the current target
       TTHREAD_TLS(T*) ptr = NULL;

Here is some output from root-config:
root-config --cxx: clang++
root-config --cc: clang
root-config --f77: gfortran-mp-5
root-config --ld: clang++

**Comment by kratsg** [comment]
Try CC=clang

That's what the environment shows.

**Comment by ndawe** [comment]
Yes, that's what @jhetherly originally tried above.

**Comment by kratsg** [comment]
Didn't notice. I wonder what's going on with Apple's clang. I wonder if you're using an Xcode clang (or if you did something like `xcode-select --install` instead?) If you have brew, maybe a `brew doctor` might point an issue that isn't obvious.

**Comment by jhetherly** [comment]
No, I'm using clang 3.7 from Macports (llvm version 3.7 as well):

clang version 3.7.0 (trunk 241984)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

I've installed ROOT and other software using this compiler. I'm not sure that could be it. I'm current compiling an older version of ROOT to see if that could help.

**Comment by piti118** [comment]
try 
`CC=clang++ CXX= clang++ pip install root-numpy`

**Comment by jhetherly** [comment]
Thus far I've tried (both ROOT 6.02/12 and 6.04/02):
pip install root_numpy      # gcc complains of unrecognized command line argument
env CC=clang pip install root_numpy      # clang complains of thread local
env CC=clang++ pip install root_numpy      # clang complains of thread local
env CC=clang CXX=clang++ pip install root_numpy      # clang complains of thread local
env CC=clang++ CXX=clang++ pip install root_numpy      # clang complains of thread local

I think the issue ROOT was having was fixed in ROOT 6.02/12. However, I believe they used a preprocessor flag to bypass the thread local issue. Unless root_numpy defines the same flag it will keep failing. I can try to look at what ROOT's solution is sometime soon.
I think what is more troubling is that it picks up gcc if I don't specify the compiler. I thought it was supposed to get the compiler from root-config (which does indeed show it's compiled with clang).

**Comment by jhetherly** [comment]
I'll have to play around with this later, but for now I've found that the following preprocessor directives are responsible for determining with type of thread storage to use:
`__CINT__`
`R__HAS_THREAD_LOCAL`
`R__HAS___THREAD`
`R__HAS_DECLSPEC_THREAD`
`R__HAS_PTHREAD`

I'm not sure which one ROOT chooses for my installation, but it looks like root_numpy is picking up the `R__HAS___THREAD` option. Can anyone point me to an area of the root_numpy code where I can change the preprocessor definitions?

**Comment by ndawe** [comment]
You can add them here:

https://github.com/rootpy/root_numpy/blob/master/setup.py#L123

**Comment by ndawe** [comment]
What does this give you?
```
root-config --cflags
```
This is how root_numpy determines what flags to use.

**Comment by jhetherly** [comment]
`root-config --cflags` gives:
`-pthread -stdlib=libc++ -std=c++11 -m64 -I/Users/jhetherly/src/root/build/6_04_02/release/include`

**Comment by jhetherly** [comment]
After hacking away over lunch I got something to work.
* Modified the `setup.py` script to account for ROOT's compiler, not Python's compiler
  * This isn't safe, but I needed to do this in order to get clang working with root_numpy (Python by default chooses the compiler it was compiled with)
```python
rootsys = os.getenv('ROOTSYS', None)
if rootsys is not None:
    try:
        root_config = os.path.join(rootsys, 'bin', 'root-config')
        root_cflags, root_ldflags = root_flags(root_config)
        has_tmva = root_has_feature('tmva', root_config)
        os.environ["CC"] = subprocess.Popen(
                [root_config, '--cc'],
                stdout=subprocess.PIPE).communicate()[0].strip()
        os.environ["CXX"] = subprocess.Popen(
                [root_config, '--cxx'],
                stdout=subprocess.PIPE).communicate()[0].strip()
#...
else:
    try:
        root_cflags, root_ldflags = root_flags()
        has_tmva = root_has_feature('tmva')
        os.environ["CC"] = subprocess.Popen(
                ['root_config', '--cc'],
                stdout=subprocess.PIPE).communicate()[0].strip()
        os.environ["CXX"] = subprocess.Popen(
                ['root_config', '--cxx'],
                stdout=subprocess.PIPE).communicate()[0].strip()
#...
```
* Then the really ugly part is that I needed to modify `$ROOTSYS/include/ThreadLocalStorage.h`. I overrode ROOT's determination of thread-local storage by writing these three lines just before it's if-else statements that actually define `TTHREAD_TLS`
  * Basically forced usage of pthread
```c++
#    undef R__HAS___THREAD
#    undef R__HAS_THREAD_LOCAL
#    define R__HAS_PTHREAD
```

I can now run root_numpy with the "testdata." I'll need to come back to this later and test with my own TTrees.
```
Python 2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
>>> import root_numpy
>>> from root_numpy import root2rec, testdata
>>> root2rec(testdata.get_filepath('single1.root'))[:20]
rec.array([(1, 1.0, 1.0), (2, 3.0, 4.0), (3, 5.0, 7.0), (4, 7.0, 10.0),
       (5, 9.0, 13.0), (6, 11.0, 16.0), (7, 13.0, 19.0), (8, 15.0, 22.0),
       (9, 17.0, 25.0), (10, 19.0, 28.0), (11, 21.0, 31.0),
       (12, 23.0, 34.0), (13, 25.0, 37.0), (14, 27.0, 40.0),
       (15, 29.0, 43.0), (16, 31.0, 46.0), (17, 33.0, 49.0),
       (18, 35.0, 52.0), (19, 37.0, 55.0), (20, 39.0, 58.0)],
      dtype=[('n_int', '<i4'), ('f_float', '<f4'), ('d_double', '<f8')])
```

**Comment by ndawe** [comment]
I think this must be a local issue with your setup. I'll close this for now and we can reopen later if needed.

It's best to use the same compiler for everything (ROOT, python, root_numpy, etc.).
