### ISSUE TITLE
Convert numpy recarrays with subarrays to branches with more than 1 value

### ISSUE THREAD

**Issue by MaxNoe** [rootpy/root_numpy#221]
It would be nice if  `root_numpy` could also convert recarrays with subarrays (`dtype('key', dtype, N)`) to root trees with branches `dtype[N]`.

Analog to:

```{python}

import ROOT
import numpy as np

f = ROOT.TFile('test.root', 'RECREATE')

array = np.zeros(2)

tree = ROOT.TTree('test', 'test')
branch = tree.Branch('test_array', array, 'D[2]')
for i in range(10):
    a = np.random.normal(0, 1, size=2)
    tree.Fill()

tree.Write()
f.Close()
```

This fails:

``` {python}
import numpy as np
from root_numpy import array2root

array = np.array([
    ([1.0, 2.0], 3), 
    ([2.0, 3.0], 6), 
], dtype=[('test_array', float, 2), ('test_number', float)]
)
array2root(array, 'test.root', 'test')

```

**Comment by ndawe** [comment]
I think you must be using an old version of root_numpy. This was added in 4.3.0. Just pip upgrade and it should work:

```python
import numpy as np
from root_numpy import array2root, root2array

array = np.array([
    ([1.0, 2.0], 3),
    ([2.0, 3.0], 6),
], dtype=[('test_array', float, 2), ('test_number', float)]
)
array2root(array, 'test.root', 'test', 'recreate')

print root2array('test.root')
```

Gives:

```
[([1.0, 2.0], 3.0) ([2.0, 3.0], 6.0)]
```

**Comment by MaxNoe** [comment]
awesome!

**Comment by ndawe** [comment]
Next thing to tackle will be the conversion of variable-length subarrays into vector branches, as listed here: https://github.com/rootpy/root_numpy/wiki

**Comment by kratsg** [comment]
On a similar vein, it would be great to get some kind of support for selections involving branches with vectors. EG: one can do `(branch[0] > X)&(branch[1] > X)` from within ROOT/PyROOT, but you cannot readily achieve the same with numpy [unfortunately]. Subvectors tend to be represented as objects (if the number of elements per event changes) or fixed type (if it's more like a fixed-size tuple per event).

**Comment by ndawe** [comment]
This already is supported since root_numpy uses the same TTreeFormula mechanism that ROOT does in TTree::Draw():

```python
import numpy as np
from root_numpy import array2root, root2array

array = np.array([
    ([1.0, 2.0], 3),
    ([2.0, 3.0], 6),
], dtype=[('test_array', float, 2), ('test_number', float)]
)
array2root(array, 'test.root', 'test', 'recreate')

print root2array('test.root', selection='(test_array[0]==1)&&(test_array[1]==2)')
```

gives:

```
[([1.0, 2.0], 3.0)]
```

**Comment by ndawe** [comment]
Also works for vector<vector<> >s

**Comment by dburns7** [comment]
Was the handling of vector branches ever implemented? When I try to read_root a file with vector branches, I get the error below, but removing these branches, the file is read fine. This functionality would be really nice.

Traceback (most recent call last):
  File "fakes.py", line 50, in <module>
    data = read_root(f, 'HZZ4LeptonsAnalysisReduced')
  File "/usr/local/lib/python2.7/dist-packages/root_pandas/readwrite.py", line 169, in read_root
    return convert_to_dataframe(arr)
  File "/usr/local/lib/python2.7/dist-packages/root_pandas/readwrite.py", line 175, in convert_to_dataframe
    df = DataFrame.from_records(array)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 841, in from_records
    columns)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 4468, in _arrays_to_mgr
    arrays = _homogenize(arrays, index, dtype)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 4777, in _homogenize
    raise_cast_failure=False)
  File "/usr/lib/python2.7/dist-packages/pandas/core/series.py", line 2600, in _sanitize_array
    raise Exception('Data must be 1-dimensional')
Exception: Data must be 1-dimensional

**Comment by kratsg** [comment]
@dburns7 I implemented it and it works fine. The error looks like a root_pandas problem. Did you try using root_numpy directly to load it in without pandas first?

**Comment by ndawe** [comment]
@kratsg implemented 2D vector handling while 1D vector handling has been in for a long time.

That pandas exception looks like it can't handle multidimensional arrays somewhere.
