### ISSUE TITLE
Support of more-then-binary operations

### ISSUE THREAD

**Issue by arogozhnikov** [rootpy/root_numpy#222]
Hi, there is an option in `root_numpy` to read different expression like `branches=['mu1_P + mu2_P']`.

It seems this option would be very useful if I was able to use more than two operands in expression.
Do you plan to handle non-trivial expressions?

**Comment by arogozhnikov** [comment]
Huh, sorry. The problem was in the absence of one of operands in a file :)

**Comment by ndawe** [comment]
No problem! Yeah, root_numpy supports the same level of complexity in the expression as TTree::Draw() does since it uses the same TTreeFormula class.
