### ISSUE TITLE
Proper way to add new column to tree in ROOT?

### ISSUE THREAD

**Issue by arogozhnikov** [rootpy/root_numpy#224]
Just curious how you add new branches. So far I know:

Way 1: make a copy with added branch.
Way 2: somehow use `rootpy`

Or maybe `root_numpy` provides some other way?

**Comment by ndawe** [comment]
You can use array2tree:

http://rootpy.github.io/root_numpy/reference/generated/root_numpy.array2tree.html

See the documentation of the optional tree argument. If you give it a tree, this tree will be extended. If a field name doesn't already exist as a branch in the tree, a new branch with that name will be added. This way you can add a single branch to an existing tree by giving array2tree a record array with a single field and a tree that you want this branch added to.

**Comment by arogozhnikov** [comment]
Great, thank you. 
After experiments I was able to get it working in the following minimal example:

```python
import numpy, root_numpy
from rootpy.io import root_open
root_numpy.array2root(numpy.array(numpy.random.random([1000, 2]), dtype=[('a', 'float64'), ('b', 'float64')] ),
                      'test.root', mode='recreate')
with root_open('test.root', mode='a') as myfile:
    new_column = numpy.array(numpy.ones([1000, 1]) , dtype=[('new', 'f8')])
    root_numpy.array2tree(new_column, tree=myfile.tree)
    myfile.write()
```

**Comment by ndawe** [comment]
Yes, I'll include an example like that in the documentation.

Glad this is working for you!
