### ISSUE TITLE
Trouble reading custom objects

### ISSUE THREAD

**Issue by maluethi** [rootpy/root_numpy#245]
I am having trouble reading a root file containing custom objects. The file is available [here](https://drive.google.com/file/d/0B3P5isMf2DUod1hrTXZ5MUZaZlE/view?usp=sharing).
I observe that root_numpy only reads the first entry of the array instead of all values when I do the following:
```
import root_numpy as nr
filename = "outs.root"
tree = "Events"
branch = "recob::Hits_LaserReco_UPlaneLaserHits_LaserHitAna.obj.fChannel"

print nr.root2array(filename, treename=tree, branches=branch)
```
This yields [ 2016.  2016.]

I expect many more entries per event, as can be seen with the TBrowser. Is this an issue connected to root_numpy not knowing the specific class I want to read? But in my eyes TBrowser should also fail in this case.

My system: Python 2.7.6, ROOT 6.02/04, root-numpy==4.4.0, Ubuntu 14.04.4 LTS

**Comment by ndawe** [comment]
You are right that it's only reading the first entry. This is because root_numpy has yet to support TClonesArrays/TBranchElements. This task is on our open tasks list: https://github.com/rootpy/root_numpy/wiki

**Comment by ndawe** [comment]
Let me see what I can do. I might be able to get this implemented soon.

**Comment by ndawe** [comment]
Getting close. Should have this done today.

**Comment by maluethi** [comment]
Sounds great. Let me know if I can help somehow.

**Comment by ndawe** [comment]
@maluethi I have it working now. See #246. If you install from my personal master branch you will get this:

```python
>>> import root_numpy as nr
>>> branch = "recob::Hits_LaserReco_UPlaneLaserHits_LaserHitAna.obj.fChannel"
>>> print nr.root2array('outs.root', 'Events', branches=branch)
[array([ 2016.,  2017.,  2018., ...,    42.,    41.,    39.])
 array([ 2016.,  2017.,  2018., ...,   274.,   273.,   272.])]
```

I'll be merging this soon and releasing a new tag once I finish updating the docs and add a new unit test.

**Comment by ndawe** [comment]
pip install --upgrade --user https://github.com/ndawe/root_numpy/zipball/master

**Comment by ndawe** [comment]
BTW great to see root_numpy being used in MicroBooNE!

**Comment by ndawe** [comment]
Just FYI, this is now included in release 4.5.0

**Comment by vgenty** [comment]
I just stumbled upon this looking to stream a custom object to numpy array. Want to drop a thank you for including this in 4.5! P.s. hey @maluethi !

**Comment by ndawe** [comment]
@vgenty no problem! Glad to see root_numpy is useful across so many experiments.
