### ISSUE TITLE
TMVA interface change in ROOT 6.07

### ISSUE THREAD

**Issue by ndawe** [rootpy/root_numpy#258]
We need to handle their new DataLoader interface in ROOT 6.07 instead of interacting directly with the Factory:

https://github.com/root-mirror/root/blob/master/tmva/tmva/inc/TMVA/DataLoader.h

Temporary installation workaround is noted in our docs:

http://rootpy.github.io/root_numpy/reference/index.html#root-numpy-tmva

**Comment by ndawe** [comment]
DataLoader exists as of v6-07-04

**Comment by kratsg** [comment]
Update -- this breaks `rootpy` installation and I can't seem to make it skip installing `root-numpy` when it's already installed:

https://gist.github.com/kratsg/dbf6c3ae3adccf8f933c174321c6944e

**Comment by ndawe** [comment]
Now done in #291
