### ISSUE TITLE
Use np.fromiter for GeneratorTypes

### ISSUE THREAD

**Issue by parnmatt** [rootpy/root_numpy#259]
https://github.com/rootpy/root_numpy/blob/master/root_numpy/_hist.py#L47

`np.asarray` will take any array-like structure and return an array; however this doesn't work for generators/iterators. `np.fromiter` will work for any iterable.

`array = np.fromiter(array, dtype=np.double)` in theory should do exactly the same as what is currently used, but also accept generator-like objects too.

I'd make a pull request, but I'd rather this be discussed if this is what is wanted in the project before I do (as it may mean several similar changes throughout the codebase, and several tests to be written).

**Comment by ndawe** [comment]
fromiter is much slower than asarray. So maybe we can first detect if the input is a generator and use fromiter otherwise use asarray:

```python
import timeit

setup = '''
from numpy import ones, fromiter, asarray, int
arr = ones(1000000, dtype=int)
'''

print "fromiter: ", min(timeit.Timer('fromiter(arr, dtype=int)', setup=setup).repeat(3, 100))
print "asarray:  ", min(timeit.Timer('asarray(arr, dtype=int)', setup=setup).repeat(3, 100))
```

```
fromiter:  4.12140917778
asarray:   5.48362731934e-05
```

**Comment by kratsg** [comment]
Easiest way is to use `asarray` by default and then catch the exception and use `fromiter`. This would be very python-esque and work quickly.

**Comment by parnmatt** [comment]
@ndawe I see you're poit, it isn't very practice to have as the default. I agree with @kratsg that catcching the expectation would be best.
@kratsg that's because `xrange` isn't a generator *per se*, whereas you are constructing a generator from an iterate in the second.

**Comment by ndawe** [comment]
What about using ``inspect.isgenerator`` upfront instead of catching the exception:

```python
>>> import inspect
>>> inspect.isgenerator(range(10))
False
>>> inspect.isgenerator(xrange(10))
False
>>> inspect.isgenerator((i for i in range(10)))
True
```

**Comment by kratsg** [comment]
http://stackoverflow.com/questions/7604636/better-to-try-something-and-catch-the-exception-or-test-if-its-possible-first

**Comment by ndawe** [comment]
That is true if it results in faster cleaner code (to prefer try/except). But we should avoid doing anything with the content of the exception message.

**Comment by ndawe** [comment]
In fact, isgenerator is simply:

```python
isinstance(thing, types.GeneratorType)
```

So, something along the lines of:

```
try:
    ... = np.asarray(...)
except TypeError:
    if isinstance(thing, types.GeneratorType):
        ... = np.fromiter(...)
    else:
        raise
```

**Comment by ndawe** [comment]
Getting back to this. Generally one would use a generator if you don't want to have a big array of all values in memory at once. In that case it's better to just loop on the generator and fill the histogram accordingly. Internally converting the generator to an array in fill_hist kind of defeats the purpose of using a generator in the first place. If you really want to, then nothing is preventing you from using ``fill_hist(hist, np.fromiter(things))``. I'm just a bit hesitant to put support for generators inside fill_hist.
