### ISSUE TITLE
undefined symbols after import root_numpy

### ISSUE THREAD

**Issue by Aelphy** [rootpy/root_numpy#272]
The problem saturated after using gcc 4.9 instead of 5.4

**Comment by kratsg** [comment]
@Aelphy -- have you tried re-installing `root_numpy` after reinstalling ROOT and numpy? It sounds like a linker error.

**Comment by Aelphy** [comment]
@kratsg -- Yes. I have tried to compile two versions of ROOT. Tried different versions of numpy.
The case was I could import ROOT library into python but while importing root_numpy the error about undefined symbols occurred.
Also I have tried different versions of root_numpy. Tried to install it using pip and to setup it manually.
The only case when the problem saturated was to change gcc from version 5 to the version 4.9

**Comment by ndawe** [comment]
This is a setup problem on your system. gcc 4 and 5 are not compatible so be sure to compile everything you are using with one or the other, not a mixture of both. root_numpy etc. compiles fine with either 4.X or 5.X.

**Comment by Aelphy** [comment]
@ndawe, That could be the case. ROOT itself was compiled with gcc 4.9.
Thank you
