### ISSUE TITLE
`array2root` unable to create file on `root://eoslhcb.cern.ch//eos/...`

### ISSUE THREAD

**Issue by KonstantinSchubert** [rootpy/root_numpy#275]
So, I don't really know what I am talking about here, but...
There is this [`eos`](https://eos.readthedocs.io/en/latest/contents.html) storage at CERN and root can read/write to it using (I think), the [XRootD](http://xrootd.org/) protcol.

So whenever you open a file, [you should use](https://lhcbqa.web.cern.ch/lhcbqa/450/is-there-a-way-to-speed-up-i-o-to-eos) an url like `root://eoslhcb.cern.ch//eos/lhcb/wg/semileptonic/Bs2KmunuAna/Tuples/Bs2KMuNu_MCTUPLES_RAW_30May16/TESTFILE.root`

`root_numpy.root2array` can read from a url like this, but when I try to create a new file (using such a `root://eoslhcb.cern.ch//eos...` url, I get the following error:

```
Error in <TNetXNGFile::Open>: [ERROR] Server responded with an error: [3011] Unable to open file /eos/lhcb/user/k/koschube/[redacted]/test.root; No such file or directory
```

**Comment by kratsg** [comment]
@KonstantinSchubert - you can't normally do that. xrootd servers are normally read-only and you create files elsewhere and move them there.

**Comment by KonstantinSchubert** [comment]
okay... I guess that means you can close the issue... but where am i going to store my tuples .... :cry:

**Comment by KonstantinSchubert** [comment]
Thinking about it, I find it really surprising that root is unable to create a file on eos. Is that really true? 

(I should try it out, I know.)

**Comment by KonstantinSchubert** [comment]
Okay, I tried it. With

`inputfile = ROOT.TFile.Open("root://eoslhcb.cern.ch//eos/lhcb/user/k/koschube/test.root","RECREATE")`

I am able to open a file without issue. Maybe `root` isn't using `xrootd`, but it is definitely able to open a file directly on `eos`.

**Comment by kratsg** [comment]
Are you trying to create it in a directory that doesn't exist? Can you do your example, but with `root_numpy`?

**Comment by ndawe** [comment]
I don't know if this will change anything, but array2root's default mode is to open with "update", but you can try changing this to "recreate" or "new", etc.

http://rootpy.github.io/root_numpy/reference/generated/root_numpy.array2root.html#root_numpy.array2root

**Comment by KonstantinSchubert** [comment]
@kratsg No, it still fails.
But @ndawe  was on it: It works if I use "RECREATE" or "NEW".
In other words, "UPDATE" can not create a file on eos.

**Comment by ndawe** [comment]
Interesting... Possibly an issue to report to the ROOT devs.
