### ISSUE TITLE
fill_hist() raises error on empty 2-dimensional histograms

### ISSUE THREAD

**Issue by gbesjes** [rootpy/root_numpy#276]
When the method root_numpy.fill_hist() is called on an empty 1-dimensional array, the behaviour is different from an empty 2-dimensional (and probably also 3-dimensional) one. An error is raised in that case:

    File "/usr/local/lib/python2.7/site-packages/root_numpy/_hist.py", line 65, in fill_hist
        raise ValueError("array must be 2-dimensional")
    ValueError: array must be 2-dimensional

That strikes me as bug: a 2-dimensional array can also be empty, although its dimensionality cannot be inferred then. Perhaps if this is the case, the original input histogram could simply be returned unmodified instead. Now it's up to the user to check whether their numpy array happens to be empty, but only in case of non-1D histograms. 

*Edit: I have to correct myself here. 1D histograms in fact behave the same, but I didn't notice that as fill_hist can take 1D subsets of structured arrays fine. That is, arr["x"] can be passed for a TH1D, but not arr[["x", "y"]] for a TH2D. So I didn't run into the issue for 1D histograms earlier.

**Comment by ndawe** [comment]
``arr["x"]`` is an unstructured array while ``arr[["x", "y"]]`` is structured so won't be accepted by fill_hist. Use ``fill_hist(hist, rec2array(arr[["x", "y"]]))`` instead. ``rec2array`` turns a structured array into an array of a single dtype.

**Comment by gbesjes** [comment]
That works perfect, thanks a lot for the quick answer! I'm closing my own issue.
