### ISSUE TITLE
rec2array() creates tuples of (2,) and not (2,1) for arrays of length 1

### ISSUE THREAD

**Issue by gbesjes** [rootpy/root_numpy#285]
Hi, 

I'm running into a small issue with rec2array. Let's say that I've got 3 branches and 3 events. I use 1 branch to split the array I built from a tree on, and the others are the ones I'm interested in.

The output of rec2array() on the original array is an array with the shape (3,2). 

If I split this array in 2, it happens to be the case that 1 event ends up in one array, and 2 in the other. That second one has a shape (2,2). The first one, however, has a shape (2,) - notably not (2,1). As a result, it needs to be treated specially to be moved into (2,1) format. 

An autodetection of this happening, so that it would be an array of an array with 2 entries (i.e. (2,1), rather than just an array of 2 entries (i.e. (2,)), would be great. It would also make the return type of rec2array() more predictable.

**Comment by ndawe** [comment]
Right, rec2array currently sends the result through np.squeeze that removes outer dimensions of length one. This is to handle 3D output properly for ``(len(rec), num_things, num_fields)``. You've found the edge case where the docs are wrong in suggesting that the shape is otherwise always ``(len(rec), num_fields)``. As you suggest, it should be ``(2, 1)``. Fixing this now...

**Comment by gbesjes** [comment]
Thanks a lot! Will this be in some new versioned number that we could grab via pip or do you not foresee a release soon?

**Comment by ndawe** [comment]
Yup, as soon as this is in I'll make a new release

**Comment by ndawe** [comment]
Fixed. Will merge when CI is green. You mean't that the shape should be (1, 2) right? (2, 2) and (1, 2) since the first dimension if the number of records.

**Comment by ndawe** [comment]
The new implementation avoids np.squeeze since that blindly squashes any dimension of size 1. Not what we want.

**Comment by ndawe** [comment]
Unit test coverage is also more thorough....

**Comment by gbesjes** [comment]
Yep, indeed. My hack is now to do:

    if arr.shape == (2,):
        arr = np.array([arr])

**Comment by ndawe** [comment]
Merged. Give the master branch a try now if you can. Will release soon.
